# Generated by Django 4.1 on 2022-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('description', models.CharField(max_length=200)),
                ('dostupnost', models.CharField(max_length=200)),
                ('cena', models.IntegerField()),
            ],
        ),
    ]
