# Generated by Django 4.1 on 2022-08-30 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objekt',
            name='mistnost',
        ),
        migrations.AddField(
            model_name='objekt',
            name='kategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mistnost', to='listings.kategorie'),
        ),
        migrations.DeleteModel(
            name='Mistnost',
        ),
    ]
