# Generated by Django 4.1 on 2022-08-30 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_objekt_mistnost_objekt_kategorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='druhobjektu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='listings.objekt'),
        ),
    ]
