# Generated by Django 4.1 on 2022-08-30 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_produkt_druhobjektu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='druhobjektu',
            new_name='objekt',
        ),
    ]
