# Generated by Django 4.1 on 2022-08-31 13:33

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_druhobjektu_produkt_objekt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='pic',
            field=models.ImageField(upload_to=listings.models.img_path),
        ),
    ]
